FROM ubuntu:latest
RUN mkdir scripts
RUN cd scripts

COPY /scripts /scripts
RUN chmod +x ./scripts/buildscript.sh
RUN chmod +x ./scripts/getMod_New_Files.ps1
RUN  /scripts/buildscript.sh
#ENTRYPOINT ["pwsh", "-c"]
CMD  ["pwsh", "/scripts/getMod_New_Files.ps1"]
ENTRYPOINT ["pwsh", "-c"]
