---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-node0
  namespace: dev
spec:
  schedule: "0,15,30,45 * * * 0-6" #"0 3,22 * * 1-5" -- summer -- "0 2,23 * * 1-5" during winter GMT <Mins> <HourinGMT> <DayofMonth> <Month> <DayofWeek> Ex run 1 pm GMT every monday * 13 * * 1
  jobTemplate:
      spec:
        template:
          spec:
            tolerations:
              - key: nodename
                operator: Equal
                value: cronjob-node0
                effect: NoSchedule
            containers:
            - name: cronjob-node0
              image: azfsbkpacr.azurecr.io/az-fs-bkp:20200105_cb3dba65f5c5f4072e02f1b4668757a63d302c18
              env:
              - name: nodenumber
                value: cronjob-node0
              imagePullPolicy: Always
              volumeMounts:          
              - name: dacredsvolume
                mountPath: /etc/dacreds
            volumes:
            - name: dacredsvolume
              secret:
                secretName: spn-creds
            restartPolicy: OnFailure
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-node1
  namespace: dev
spec:
  schedule: "0,15,30,45 * * * 0-6" #"0 3,22 * * 1-5" -- summer -- "0 2,23 * * 1-5" during winter GMT <Mins> <HourinGMT> <DayofMonth> <Month> <DayofWeek> Ex run 1 pm GMT every monday * 13 * * 1
  jobTemplate:
      spec:
        template:
          spec:
            tolerations:
              - key: nodename
                operator: Equal
                value: cronjob-node1
                effect: NoSchedule
            containers:
            - name: cronjob-node1
              image: azfsbkpacr.azurecr.io/az-fs-bkp:20200105_cb3dba65f5c5f4072e02f1b4668757a63d302c18
              env:
              - name: nodenumber
                value: cronjob-node1
              imagePullPolicy: Always
              volumeMounts:          
              - name: dacredsvolume
                mountPath: /etc/dacreds
            volumes:
            - name: dacredsvolume
              secret:
                secretName: spn-creds
            restartPolicy: OnFailure
---
